# Generated by Django 5.1.7 on 2025-03-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
