# Generated by Django 5.0.2 on 2026-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('avatar', models.URLField(blank=True, help_text='URL to avatar image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Live demo URL', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('expert', 'Expert'), ('proficient', 'Proficient'), ('learning', 'Learning'), ('installed', 'Installed')], default='proficient', help_text='Proficiency level', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='version',
            field=models.CharField(blank=True, default='latest', help_text='Version e.g. 24.0.7', max_length=30),
        ),
    ]
