# Generated by Django 5.0.2 on 2026-03-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0006_testimonial_alter_contact_options_project_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(blank=True, help_text='e.g., Aug 2023', max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, help_text='e.g., Aug 2026 or No expiration', max_length=50, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, help_text='URL to credential verification', null=True)),
                ('icon', models.CharField(default='fas fa-certificate', help_text='FontAwesome icon class', max_length=50)),
            ],
        ),
    ]
